In [1]:
import pandas as pd
import sklearn

In [2]:
df=pd.read_csv("/content/Compression_ML_Dataset.csv",header=1)

In [3]:
df

,Unnamed: 0,Infill Pattern,Infill Density,Yield Tensile Strength,Failure Force,Young's Modulus,Poisson's Ratio,Density,Thermal Cond,Unnamed: 9
0,NaN,Hexagonal,60.0,90.9,7206.504478,3.85,0.4000,0.000001,0.000250,NaN
1,NaN,Hexagonal,70.0,90.9,5644.553108,3.85,0.4000,0.000001,0.000250,NaN
2,NaN,Hexagonal,80.0,90.9,5885.749234,3.85,0.4000,0.000001,0.000250,NaN
3,NaN,Hexagonal,90.0,90.9,6774.868151,3.85,0.4000,0.000001,0.000250,NaN
4,NaN,Cubic,50.0,90.9,4069.865900,3.85,0.4000,0.000001,0.000250,NaN
...,...,...,...,...,...,...,...,...,...,...
68,NaN,Concentric,80.0,54.1,4878.862177,3.45,0.3899,0.000001,0.000144,NaN
69,NaN,Concentric,90.0,54.1,3918.599811,3.45,0.3899,0.000001,0.000144,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['Unnamed: 0', 'Infill Pattern ', 'Infill Density',
       'Yield Tensile Strength', 'Failure Force', 'Young's Modulus',
       'Poisson's Ratio', 'Density', 'Thermal Cond', 'Unnamed: 9'],
      dtype='object')

In [5]:
df=df.drop(["Unnamed: 0",'Unnamed: 9'],axis="columns")

In [6]:
df

,Infill Pattern,Infill Density,Yield Tensile Strength,Failure Force,Young's Modulus,Poisson's Ratio,Density,Thermal Cond
0,Hexagonal,60.0,90.9,7206.504478,3.85,0.4000,0.000001,0.000250
1,Hexagonal,70.0,90.9,5644.553108,3.85,0.4000,0.000001,0.000250
2,Hexagonal,80.0,90.9,5885.749234,3.85,0.4000,0.000001,0.000250
3,Hexagonal,90.0,90.9,6774.868151,3.85,0.4000,0.000001,0.000250
4,Cubic,50.0,90.9,4069.865900,3.85,0.4000,0.000001,0.000250
...,...,...,...,...,...,...,...,...
68,Concentric,80.0,54.1,4878.862177,3.45,0.3899,0.000001,0.000144
69,Concentric,90.0,54.1,3918.599811,3.45,0.3899,0.000001,0.000144
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df=df.dropna( axis=0, how="any", thresh=None, subset=None, inplace=False)

In [8]:
dummies1 = pd.get_dummies(df)
dummies1

,Infill Density,Yield Tensile Strength,Failure Force,Young's Modulus,Poisson's Ratio,Density,Thermal Cond,Infill Pattern _Concentric,Infill Pattern _Cubic,Infill Pattern _Hexagonal
0,60.0,90.9,7206.504478,3.85,0.4000,0.000001,0.000250,0,0,1
1,70.0,90.9,5644.553108,3.85,0.4000,0.000001,0.000250,0,0,1
2,80.0,90.9,5885.749234,3.85,0.4000,0.000001,0.000250,0,0,1
3,90.0,90.9,6774.868151,3.85,0.4000,0.000001,0.000250,0,0,1
4,50.0,90.9,4069.865900,3.85,0.4000,0.000001,0.000250,0,1,0
...,...,...,...,...,...,...,...,...,...,...
65,50.0,54.1,3017.644377,3.45,0.3899,0.000001,0.000144,1,0,0
66,60.0,54.1,3490.745453,3.45,0.3899,0.000001,0.000144,1,0,0
67,70.0,54.1,4348.560519,3.45,0.3899,0.000001,0.000144,1,0,0
68,80.0,54.1,4878.862177,3.45,0.3899,0.000001,0.000144,1,0,0
69,90.0,54.1,3918.599811,3.45,0.3899,0.000001,0.000144,1,0,0

In [9]:
final=dummies1.drop(['Infill Pattern _Concentric'],axis="columns")

In [10]:
final

,Infill Density,Yield Tensile Strength,Failure Force,Young's Modulus,Poisson's Ratio,Density,Thermal Cond,Infill Pattern _Cubic,Infill Pattern _Hexagonal
0,60.0,90.9,7206.504478,3.85,0.4000,0.000001,0.000250,0,1
1,70.0,90.9,5644.553108,3.85,0.4000,0.000001,0.000250,0,1
2,80.0,90.9,5885.749234,3.85,0.4000,0.000001,0.000250,0,1
3,90.0,90.9,6774.868151,3.85,0.4000,0.000001,0.000250,0,1
4,50.0,90.9,4069.865900,3.85,0.4000,0.000001,0.000250,1,0
...,...,...,...,...,...,...,...,...,...
65,50.0,54.1,3017.644377,3.45,0.3899,0.000001,0.000144,0,0
66,60.0,54.1,3490.745453,3.45,0.3899,0.000001,0.000144,0,0
67,70.0,54.1,4348.560519,3.45,0.3899,0.000001,0.000144,0,0
68,80.0,54.1,4878.862177,3.45,0.3899,0.000001,0.000144,0,0
69,90.0,54.1,3918.599811,3.45,0.3899,0.000001,0.000144,0,0

In [11]:
x= final.drop(['Failure Force','Density','Thermal Cond'],axis='columns')
x

,Infill Density,Yield Tensile Strength,Young's Modulus,Poisson's Ratio,Infill Pattern _Cubic,Infill Pattern _Hexagonal
0,60.0,90.9,3.85,0.4000,0,1
1,70.0,90.9,3.85,0.4000,0,1
2,80.0,90.9,3.85,0.4000,0,1
3,90.0,90.9,3.85,0.4000,0,1
4,50.0,90.9,3.85,0.4000,1,0
...,...,...,...,...,...,...
65,50.0,54.1,3.45,0.3899,0,0
66,60.0,54.1,3.45,0.3899,0,0
67,70.0,54.1,3.45,0.3899,0,0
68,80.0,54.1,3.45,0.3899,0,0
69,90.0,54.1,3.45,0.3899,0,0

In [12]:
y=final['Failure Force']
y

0     7206.504478
1     5644.553108
2     5885.749234
3     6774.868151
4     4069.865900
         ...
65    3017.644377
66    3490.745453
67    4348.560519
68    4878.862177
69    3918.599811
Name: Failure Force, Length: 70, dtype: float64

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [32]:
'''
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
model = Pipeline([('poly', PolynomialFeatures(degree = 2)),('linear', LinearRegression(fit_intercept=False))])
model.fit(X_train,y_train)
score_train = model.score(X_train, y_train)
score_test = model.score(X_test, y_test)
print('R^2 score for training data = %10.4f'%(score_train))
print('R^2 score for testing data  = %10.4f'%(score_test))'''

"\nfrom sklearn.preprocessing import PolynomialFeatures\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.pipeline import Pipeline\nmodel = Pipeline([('poly', PolynomialFeatures(degree = 2)),('linear', LinearRegression(fit_intercept=False))])\nmodel.fit(X_train,y_train)\nscore_train = model.score(X_train, y_train)\nscore_test = model.score(X_test, y_test)\nprint('R^2 score for training data = %10.4f'%(score_train))\nprint('R^2 score for testing data  = %10.4f'%(score_test))"

In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso

model=Lasso(alpha= 0.1 , max_iter = 5000)
model.fit(X_train,y_train)
score_train = model.score(X_train, y_train)
score_test = model.score(X_test, y_test)
print('R^2 score for training data = %10.4f'%(score_train))
print('R^2 score for testing data  = %10.4f'%(score_test))

R^2 score for training data =     0.9614
R^2 score for testing data  =     0.9197

In [30]:
'''
from sklearn.neural_network import MLPRegressor
nnmodel = MLPRegressor(hidden_layer_sizes=(256,124), alpha=0.1,max_iter=5000,random_state=None)
nnmodel.fit(X_train,y_train)
score_train = nnmodel.score(X_train, y_train)
score_test = nnmodel.score(X_test, y_test)
print('R^2 score for training data = %10.4f'%(score_train))
print('R^2 score for testing data  = %10.4f'%(score_test))
'''

"\nfrom sklearn.neural_network import MLPRegressor\nnnmodel = MLPRegressor(hidden_layer_sizes=(256,124), alpha=0.1,max_iter=5000,random_state=None)\nnnmodel.fit(X_train,y_train)\nscore_train = nnmodel.score(X_train, y_train)\nscore_test = nnmodel.score(X_test, y_test)\nprint('R^2 score for training data = %10.4f'%(score_train))\nprint('R^2 score for testing data  = %10.4f'%(score_test))\n"

In [34]:
import pickle
with open("Compression_Failure_Force_Predictor","wb") as f:
  pickle.dump(model,f)